spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dbms?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: 123Yzm66
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    org.mybatis: DEBUG

server:
  port: 8080
